import { writeFileSync } from "fs";
import { describe, expect, it } from "vitest";

import { BARS, barsKey } from "../src/bars";
import { Engine } from "../src/engine";

import { lockInThreshold } from "./analysis";
import { Simulator } from "./simulator";

// The lock-in bars are what the engine expects to score from carrying on, so
// they depend on how well the engine plays. They're generated by playing it
// against the simulator, and checked here so that any change to the engine or
// the simulator that moves them fails until they're regenerated (yarn bars).

const GAMES_AFTER = [1, 2, 3, 4];

function engineScores(boosts: [number, number, number], days: number, firstSeed: number) {
  const scores: number[] = [];
  for (let day = 0; day < days; day++) {
    const sim = new Simulator({ seed: firstSeed + day, boosts });
    new Engine(sim, {
      rewards: {},
      games: 5,
      samples: 16,
      lockIn: false,
      toBeat: 0,
    }).run();
    scores.push(...sim.finalScores);
  }
  return scores;
}

function bars(scores: number[]): number[] {
  return GAMES_AFTER.map((n) => Math.round(lockInThreshold(scores, n)));
}

describe("lock-in bars", () => {
  // Fresh seeds, so this checks the bars are right rather than reproducible.
  // 200 games put each bar within about 25 cheese of the truth, so a 75
  // tolerance is about three standard errors.
  it.each([
    [0, 0, 0],
    [3, 3, 3],
  ] as [number, number, number][])(
    "match what the engine scores with boosts %i/%i/%i",
    { timeout: 300_000 },
    (...boosts) => {
      const expected = BARS[barsKey(boosts)];
      const actual = bars(engineScores(boosts, 40, 100_000));
      actual.forEach((bar, i) => expect(Math.abs(bar - expected[i])).toBeLessThan(75));
    },
  );
});

it.runIf(process.env.GENERATE_BARS)("generates the bars", { timeout: 3_600_000 }, () => {
  const table: Record<string, number[]> = {};
  for (let a = 0; a <= 3; a++) {
    for (let b = a; b <= 3; b++) {
      for (let c = b; c <= 3; c++) {
        table[`${a},${b},${c}`] = bars(engineScores([a, b, c], 100, 1));
      }
    }
  }
  // Bars for 1, 2, 3 and 4 games still to play, keyed by sorted potion turns
  writeFileSync(
    new URL("../src/data/bars.json", import.meta.url),
    `${JSON.stringify(table, null, 2)}\n`,
  );
});
