import BARS_DATA from "./data/bars.json";

// The score worth locking in, given the turns of each Bastille potion effect
// (in any order) and how many games are left to play after this one (1-4).
// With no games left, lock in anything. Generated by `yarn bars`, checked by
// test/bars.test.ts.
export const BARS: Record<string, number[]> = BARS_DATA;

export function barsKey(boosts: number[]): string {
  return boosts
    .map((b) => Math.min(3, Math.max(0, b)))
    .sort((x, y) => x - y)
    .join(",");
}

export function lockInBar(boosts: number[], gamesAfter: number): number {
  if (gamesAfter <= 0) return -Infinity;
  const bars = BARS[barsKey(boosts)];
  return bars[Math.min(gamesAfter, bars.length) - 1];
}
